apiVersion: v1
kind: ServiceAccount
metadata: 
  labels:
    name: helm-repo-sa
    app.kubernetes.io/instance: helmrepos.operator.ibm.com
    app.kubernetes.io/managed-by: helmrepos.operator.ibm.com
    app.kubernetes.io/name: helmrepos.operator.ibm.com
    helm.sh/chart: helm-repo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-repo-privileged-role
rules:
- apiGroups:
  - security.openshift.io 
  resources:
  - securitycontextconstraints 
  resourceNames:
  - privileged
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-repo-privileged
subjects:
- kind: ServiceAccount
  name: helm-repo-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-repo-privileged-role