apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    name: ibm-helm-repo-operator
    app.kubernetes.io/instance: helmrepos.operator.ibm.com
    app.kubernetes.io/managed-by: helmrepos.operator.ibm.com
    app.kubernetes.io/name: helmrepos.operator.ibm.com
subjects:
- kind: ServiceAccount
  name: ibm-helm-repo-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-helm-repo-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-helm-repo-operator
subjects:
- kind: ServiceAccount
  name: ibm-helm-repo-operator
  namespace: ibm-common-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-helm-repo-operator