apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: ibm-helm-repo-operator
    app.kubernetes.io/instance: helmrepos.operator.ibm.com
    app.kubernetes.io/managed-by: helmrepos.operator.ibm.com
    app.kubernetes.io/name: helmrepos.operator.ibm.com
