apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helmrepos.operator.ibm.com
  # labels:
  #   app.kubernetes.io/instance: 
  #     type: string
  #   app.kubernetes.io/managed-by: 
  #     type: string
  #   app.kubernetes.io/name: 
  #     type: string
spec:
  group: operator.ibm.com
  names:
    kind: HelmRepo
    listKind: HelmRepoList
    plural: helmrepos
    singular: helmrepo
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
